config/routes.rb
Rails.application.routes.draw do

  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]

  namespace :admin do
    resources :users
  end

  root to: 'movies#index'

  get '/search', to: 'movies#search'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :reviews, dependent: :destroy

  validates :email, presence: true

  validates :firstname, presence: true

  validates :lastname, presence: true

  validates :password, length: { in: 6..20 }, on: :create

  def full_name
    "#{firstname} #{lastname}"
  end

  def admin?
    admin
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  

  before_action :load_user, only: [:show, :edit, :update]

  def index
    if current_user.admin == true
      @users = User.order("firstname").page(params[:page]).per(5)
    else
      redirect_to root_url, alert: "You don't have admin access"
    end
  end

  def new
    @user = User.new
  end

  def create
   params[:admin] == 1 ? params[:admin] = true : false
  
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path, notice: "You've created a user called #{@user.firstname}."
    else
      render :new
    end
  end

  def show
    # @user = User.find(params[:id])
  end

  def edit
    # @user = User.find(params[:id])
  end

  def update
    # @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to admin_users_path
    else
      redirect_to edit_admin_user_path, notice: "You suck at life."
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path, notice: "You've deleted #{@user.full_name}'s account."
  end

  protected

  def load_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation, :admin)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: 201, acl: :public_read)
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id # auto log in
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end

  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h1>Admin Edit Screen</h1>

<%= form_for [:admin,@user] do |f| %>
  <div>
    <%= f.label "firstname" %><br>
    <%= f.text_field "firstname" %>
  </div>
  <div>
    <%= f.label "lastname" %><br>
    <%= f.text_field "lastname" %>
  </div>
  <div>
    <%= f.label "email" %><br>
    <%= f.text_field "email" %>
  </div>
  <div>
    <%= f.submit "Submit" %> 
  </div>
<% end %>

app/views/admin/users/index.html.erb
<h1 class="admin-title">Admin Users List</h1>

<div style="text-align: center;"><%= link_to "Create New User", new_admin_user_path, :class => "button" %></div><br>
<div class="row">
  <div class="large-6 large-centered columns">
  <%= paginate @users %>
  <table>
    <tr>
      <td style="color: #f04124;"> Firstname </td>
      <td style="color: #f04124;"> Lastname </td>
      <td style="color: #f04124;"> Email </td>
      <td style="color: #f04124;"> ID </td>
      <td></td>
      <td style="color: #f04124;"> Admin</td>
    </tr>
      <% @users.each do |user| %>
    <tr>
      <td><%= user.firstname %></td> 
      <td><%= user.lastname %></td>
      <td><%= link_to user.email, admin_user_path(user) %></td>
      <td><%= user.id %></td>
      <td></td>
      <td><%= user.admin? %></td>
    </tr>
      <% end %>
  </table>
  </div>
</div>

app/views/admin/users/new.html.erb
<h1 class="page-titles" style="text-align: center;">Admin Create User</h1>
  <div class="row">
    <div class="large-4 large-centered columns">
      <%= form_for [:admin, @user] do |f| %>
      <div>
        <%= f.text_field "email", :placeholder => "Email" %>
      </div>
      <div> 
        <%= f.text_field "firstname", :placeholder => "First Name" %>
      </div>
      <div>
        <%= f.text_field "lastname", :placeholder => "Last Name" %>
      </div>
      <div>
        <%= f.password_field "password", :placeholder => "Password" %>
      </div>
      <div>
        <%= f.password_field "password_confirmation", :placeholder => "Password Confirmation" %>
      </div>
      <div>
        <%= f.label "admin", "Admin?" %><br>
        <%= f.check_box "admin" %>
      </div>
      <div><%= f.submit "Submit", :class => "button" %></div>
      <% end %>
    </div>
  </div>

app/views/admin/users/show.html.erb
<div class="container-bg-box">
  <h2 class="edit-user"><%= @user.full_name %></h2>
  <hr>
  <p class="user-details">Email: <%= @user.email %></p>
  <p class="user-details">Admin: <%= @user.admin? %></p>
  <p class="user-details">Created at: <%= @user.created_at %></p>
  <hr>
  <%= link_to "Edit details", edit_admin_user_path(@user) %><br>
  <%= link_to "Delete user", admin_user_path(@user), method: :delete, :data => {:confirm => 'Are you sure?'} %>
</div>