config/routes.rb
Rails.application.routes.draw do

  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]

  namespace :admin do
    resources :users
  end

  root to: 'movies#index'

  get '/search', to: 'movies#search'

end

app/views/layouts/_floatnav.html.erb
<div class="off-canvas-wrap docs-wrap" data-offcanvas>
  <div class="inner-wrap">
    <nav class="tab-bar">
      <section class="left-small">
        <a class="left-off-canvas-toggle menu-icon" ><span></span></a>
      </section>

      <section class="middle tab-bar-section">
        <h1 class="title">Putrid Kale</h1>
      </section>

      <section class="right-small">
        <a class="right-off-canvas-toggle menu-icon" ><span></span></a>
      </section>
    </nav>

    <aside class="left-off-canvas-menu">
      <ul class="off-canvas-list">
        <li><label>Putrid Kale</label></li>
        <li><%= link_to "Search", search_path %></li>
        <li><%= link_to "Submit Film", new_movie_path %></li>
      </ul>
    </aside>

  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <% if current_user %>
      <span class="current-user-title">Signed in as: </span> <span class="current-user"><%= current_user.full_name %></span> <%= link_to "Log out", session_path("current"), method: :delete %> | <%= link_to "Admin", admin_users_path %>
    <% else %>
      <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
    <% end %>
  </small>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name" style="text-align: center;"><h1><a href="/">Putrid Kale</a></h1></li>
  </ul>
  <!-- Top Bar Section -->
  <section class="top-bar-section">
    <!-- Top Bar Left Nav Elements -->
    <ul class="left">
      <ul class="button-group">
        <li class="has-form">
          <%= link_to "Search", search_path, :class => "button" %>
        </li>
        <li class="has-form">
          <%= link_to "Submit Film", new_movie_path, :class => "button" %>
        </li>
      </ul>
    </ul>
    <!-- Top Bar Right Nav Elements -->
    <ul class="right">
      <!-- Anchor -->
      <li> <%= render :partial => 'layouts/footer' %></li>
      <li class="divider"></li>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <div id="bg-filter"></div>
  <%= render :partial => 'layouts/navbar' %>
    <div class="row">
      <div class="large-12 columns"><%= yield %></div>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>